export const black = '#000'
export const grayLight = '#888'
export const grayXLight = '#ccc'
export const grayDark = '#222'
export const orange = '#ffa500'
export const red = '#ff0000'
export const white = '#fff'